compile:
	npx hardhat compile

deploy_Celestial:
	npx hardhat run ignition/modules/celestial.ts --network fuji

deploy_Gladiator:
	npx hardhat run ignition/modules/gladiator.ts --network fuji

verify_Celestial:
	npx hardhat verify --network fuji 0xa1068a7ccFC10e8Ca038d5C8169C942Fd593cD65

verify_Gladiator:
	npx hardhat verify --network fuji 0x65F227c3243A5E42875b84170CD2f0E8ec6abD61