compile:
	npx hardhat compile

deploy_Celestial:
	npx hardhat run ignition/modules/celestial.ts --network eduChain

deploy_Gladiator:
	npx hardhat run ignition/modules/gladiator.ts --network eduChain

verify_Celestial:
	npx hardhat verify --network eduChain 0x6812362C9c19e76fb3b91e18f83b6BE6D17B7e0c

verify_Gladiator:
	npx hardhat verify --network eduChain 0x936e03DF2F9c34637d716b1312473b7DaB326533