compile:
	npx hardhat compile

deploy_Celestial:
	npx hardhat run ignition/modules/celestial.ts --network fuji

deploy_Gladiator:
	npx hardhat run ignition/modules/gladiator.ts --network fuji

verify_Celestial:
	npx hardhat verify --network fuji 0x14Df5a95729215AcE473Df74aCd9619E301048D9

verify_Gladiator:
	npx hardhat verify --network fuji 0x3a11e676F587B3020692be9738B1b1288b50A1aF